# General Settings
locale                 : "en-US"
title                  : "Luis Chancí"
title_separator        : "-"
name                   : &name "Luis Chancí"
job_title              : "Research Economist"
description            : &description "Forth-year Ph.D. student in Economics."
url                    : "https://luischanci.github.io"
repository             : "luischanci/luischanci.github.io"
avatar                 : "/assets/images/luischanci.jpg"

# Site Author
author:
  name             : "Chancí"
  email            : "lchanci1@binghamton.edu"
  avatar           : /assets/images/luischanci.jpg
  favicon          : /assets/images/logo.png
  twitter_handler  : "davidchanci"
  analytics_code   : "UA-136801897-1"
  disqus           : "luischanci"
  github           : "luischanci"
  orcid            : "https://orcid.org/0000-0002-6239-2156"
  googlescholar    : "https://scholar.google.com/citations?user=H3S8NIUAAAAJ&hl=es"

# Social Accounts
social_networks:
-  { name: facebook, url: '' }
-  { name: twitter, url: 'http://twitter.com/davidchanci' }
-  { name: instagram, url: '' }
-  { name: google-plus, url: '' }
-  { name: linkedin, url: '' }
-  { name: skype, url: '' }
-  { name: github, url: 'https://github.com/luischanci' }
-  { name: codepen, url: '' }
-  { name: stack-overflow, url: '' }
-  { name: dribbble, url: '' }
-  { name: behance, url: '' }
-  { name: pinterest, url: '' }
-  { name: tumblr, url: '' }
-  { name: youtube, url: '' }
-  { name: vimeo, url: '' }
-  { name: vine, url: '' }
-  { name: 500px, url: '' }
-  { name: flickr, url: 'https://www.flickr.com/davidchanci/' }
-  { name: spotify, url: '' }
-  { name: steam, url: '' }
-  { name: wordpress, url: '' }
-  { name: xing, url: '' }
-  { name: bitcoin, url: '' }
-  { name: pocket, url: '' }
-  { name: applemusic, url: '' }

# Modules Settings
show_categories: 1
show_tags: 1
show_email: 1
show_rss: 1
show_comments: 0
show_menu: 1
fixed_sidebar: 1

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _teaching
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  # _research
  - scope:
      path: ""
      type: research
    values:
      layout: single
      author_profile: true
      share: true
      comments: true

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------
# Collections
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  research:
    output: true
    permalink: /:collection/:path/

# Includes
include: ["_pages"]

# Outputting
permalink: /:categories/:title/
category_dir: categories

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from
# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# Pagination
paginate: 10
paginate_path: "/page:num/"

# Conversion
markdown: kramdown
excerpt_separator: <!--more-->

# Assets Settings
sass:
  sass_dir: assets/partials
  style: compressed

# Fixes (bundle exec error)
exclude: [vendor]

# Syntax highlighting
highlighter: rouge

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
#    css_class: 'highlight'
